module Inter.Api.Sitemap.Xsl where

import Proem

import Config.PublicConfig (publicConfig, toAbsolute_)
import Data.String as String
import Data.String.Pattern (Pattern(..), Replacement(..))
import Effect.Aff (Aff)
import Inter.Api.ApiM (Context)
import Node.Encoding (Encoding(..))
import Node.HTTP.OutgoingMessage (setHeader, toWriteable)
import Node.HTTP.ServerResponse (setStatusCode, toOutgoingMessage)
import Node.HTTP.Types (IMServer, IncomingMessage, ServerResponse)
import Node.Stream (end, writeString)

handleSitemapXsl :: Context -> IncomingMessage IMServer -> ServerResponse -> Aff Ɩ
handleSitemapXsl _ _ res = ʌ do
  setStatusCode 200 res
  let msg = toOutgoingMessage res
  setHeader "Content-Type" "text/xsl; charset=utf-8" msg
  _ <- writeString (toWriteable msg) UTF8 (sitemapXsl (toAbsolute_ publicConfig.ui.host "/"))
  end (toWriteable msg)

-- Change only when the xsl changes.
-- That will force the rebuild of the sitemap visualization in browsers 
-- (e.g. Nginx cache proxy in front of the API server).
sitemapXslVersion = 4 :: Int

sitemapXsl :: String -> String
sitemapXsl booksUrl = String.replaceAll (Pattern "${booksUrl}") (Replacement booksUrl)
  """<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:html="http://www.w3.org/TR/REC-html40"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #333; margin: 0; padding: 2rem; background: #f9f9fa; }
          #container { max-width: 1000px; margin: 0 auto; }
          h1 { margin: 0 0 0.5rem 0; font-size: 1.8rem; color: #111; }
          p { margin: 0 0 1.5rem 0; color: #555; font-size: 0.95rem; line-height: 1.5; }
          a { color: #0052cc; text-decoration: none; }
          a:hover { text-decoration: underline; }
          table { width: 100%; border-collapse: collapse; background: #fff; box-shadow: 0 1px 3px rgba(0,0,0,0.1); border-radius: 4px; overflow: hidden; font-size: 0.9rem; }
          th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #eee; }
          th { background: #f4f5f7; font-weight: 600; color: #333; border-bottom: 2px solid #dfe1e6; }
          tr:last-child td { border-bottom: none; }
          tr:hover td { background: #fafbfc; }
        </style>
      </head>
      <body>
        <div id="container">
          <h1>XML Sitemap</h1>
          <p>Generated by <a href="${booksUrl}">Books</a>, this is an XML Sitemap, meant for consumption by search engines.<br/>You can find more information about XML sitemaps on <a href="https://sitemaps.org">sitemaps.org</a>.</p>
          <xsl:if test="count(sitemap:sitemapindex/sitemap:sitemap) &gt; 0">
            <p>This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
            <table>
              <thead>
                <tr>
                  <th>Sitemap</th>
                  <xsl:if test="sitemap:sitemapindex/sitemap:sitemap/sitemap:lastmod">
                    <th>Last Modified</th>
                  </xsl:if>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <xsl:if test="../sitemap:sitemap/sitemap:lastmod">
                      <td><xsl:value-of select="sitemap:lastmod"/></td>
                    </xsl:if>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
          <xsl:if test="count(sitemap:urlset/sitemap:url) &gt; 0">
            <p>This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
            <table>
              <thead>
                <tr>
                  <th>URL</th>
                  <xsl:if test="sitemap:urlset/sitemap:url/sitemap:lastmod">
                    <th>Last Modified</th>
                  </xsl:if>
                </tr>
              </thead>
              <tbody>
                <xsl:for-each select="sitemap:urlset/sitemap:url">
                  <tr>
                    <td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
                    <xsl:if test="../sitemap:url/sitemap:lastmod">
                      <td><xsl:value-of select="sitemap:lastmod"/></td>
                    </xsl:if>
                  </tr>
                </xsl:for-each>
              </tbody>
            </table>
          </xsl:if>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet>"""
