module Core.Mod.Projection.Index where

import Core.Feat.Membership.Projection.Index (MEMBERSHIP_PROJECTION_READ_FIND, MEMBERSHIP_PROJECTION_READ_SYNC_PROJECT, MEMBERSHIP_PROJECTION_WRITE_OPS, MembershipProjectionRow)
import Core.Feat.Newsletter.Projection.Index (NEWSLETTER_PROJECTION_READ_FIND, NEWSLETTER_PROJECTION_READ_SYNC_PROJECT, NEWSLETTER_PROJECTION_WRITE_OPS, NewsletterProjectionRow)
import Core.Feat.Reference.Projection.Index (REFERENCE_PROJECTION_READ_FIND, REFERENCE_PROJECTION_READ_SYNC_PROJECT, REFERENCE_PROJECTION_WRITE_OPS, ReferenceProjectionRow)
import Core.Feat.Review.Projection.Index (REVIEW_PROJECTION_READ_FIND, REVIEW_PROJECTION_READ_SYNC_PROJECT, REVIEW_PROJECTION_WRITE_OPS, ReviewProjectionRow)
import Core.Feat.Sitemap.Projection.Index (SITEMAP_PROJECTION_READ_FIND, SITEMAP_PROJECTION_READ_SYNC_PROJECT, SITEMAP_PROJECTION_WRITE_OPS, SitemapProjectionRow)
import Type.Row (type (+))

type ProjectionRow =
  ReviewProjectionRow
    + SitemapProjectionRow
    + NewsletterProjectionRow
    + ReferenceProjectionRow
    + MembershipProjectionRow
    + ()

type PROJECTION_WRITE_OPS fx =
  REVIEW_PROJECTION_WRITE_OPS
    + SITEMAP_PROJECTION_WRITE_OPS
    + NEWSLETTER_PROJECTION_WRITE_OPS
    + REFERENCE_PROJECTION_WRITE_OPS
    + MEMBERSHIP_PROJECTION_WRITE_OPS
    + fx

type PROJECTION_READ_FIND fx =
  REVIEW_PROJECTION_READ_FIND
    + SITEMAP_PROJECTION_READ_FIND
    + NEWSLETTER_PROJECTION_READ_FIND
    + REFERENCE_PROJECTION_READ_FIND
    + MEMBERSHIP_PROJECTION_READ_FIND
    + fx

type PROJECTION_READ_SYNC_PROJECT fx =
  REVIEW_PROJECTION_READ_SYNC_PROJECT
    + SITEMAP_PROJECTION_READ_SYNC_PROJECT
    + NEWSLETTER_PROJECTION_READ_SYNC_PROJECT
    + REFERENCE_PROJECTION_READ_SYNC_PROJECT
    + MEMBERSHIP_PROJECTION_READ_SYNC_PROJECT
    + fx

type PROJECTION_READ fx =
  PROJECTION_READ_FIND
    + PROJECTION_READ_SYNC_PROJECT
    + fx
